### PR TITLE
Fixed loading issue in example

### PR DESCRIPTION
**Pull request by mbkupfer**
I was getting the following error: 
`Loading failed for the <script> with source “file:///dist/build.js”`

After adding this minor change it worked. Likely has to do with a conflict on windows os.

### CODE REVIEW

**Comment by chrisvfritz** [comment]
This kind of routing needs a domain to work, so running `npm run dev`/`yarn dev` locally or publishing to a web server that supports SPAs should work. Did you get an error using either of those strategies?

**Comment by mbkupfer** [comment]
I haven't tried any of those strategies. I loaded it in the browser using the `file://` protocol
i.e: `file:///C:/Users/mkupfer/path/to/repo/vue-2.0-simple-routing-example/index.html`

Update: `npm run dev` does work using prior `index.html`. My reasoning to try  `file://` protocol is to avoid using any server and allow it to run on client side. Is there something I'm missing. Btw, I am fairly new to web dev.

**Comment by mbkupfer** [comment]
@chrisvfritz could you confirm that I have this working right? I'm getting the 404.vue page as the first rendered item. All the other links work though.  
image

https://mbkupfer.github.io/vue-2.0-simple-routing-example/

**Comment by chrisvfritz** [comment]
GitHub Pages doesn't support SPAs, though there are [some workarounds](https://github.com/isaacs/github/issues/408). I recommend hosts like Surge or Netlify instead.

**Comment by mbkupfer** [comment]
@chrisvfritz, ok thanks for help. I'll go ahead and close this.

**Pull request closed without merging**
